FROM vernacularai/kaldi:2019-11-23

# gRPC Pre-requisites - https://github.com/grpc/grpc/blob/master/BUILDING.md
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    build-essential \
    autoconf \
    libtool \
    pkg-config \
    libgflags-dev \
    libgtest-dev \
    clang \
    libc++-dev \
    libboost-all-dev \
    curl \
    vim

# Install gRPC
RUN cd /home/ && \
    git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc && \
    cd /home/grpc/ && \
    git submodule update --init && \
    ex -s -c '356i|CPPFLAGS += -Wno-unused-variable' -c x Makefile && \
    make -j$(nproc) && \
    make install -j$(nproc) && ldconfig && \
    cd /home/grpc/third_party/protobuf && make install && \
    rm -rf /home/grpc/

WORKDIR /home/app

COPY . .

ENV KALDI_ROOT="/home/kaldi" \
    LD_LIBRARY_PATH="/home/kaldi/tools/openfst/lib:/home/kaldi/src/lib"

RUN ls
RUN pwd
RUN make

CMD [ "./build/kaldi_serve_app" ]
