// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kaldi.proto

#include "kaldi.pb.h"
#include "kaldi.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace kaldi {

static const char* Kaldi_method_names[] = {
  "/kaldi.Kaldi/Recognize",
};

std::unique_ptr< Kaldi::Stub> Kaldi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Kaldi::Stub> stub(new Kaldi::Stub(channel));
  return stub;
}

Kaldi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Recognize_(Kaldi_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Kaldi::Stub::Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::kaldi::RecognizeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Recognize_, context, request, response);
}

void Kaldi::Stub::experimental_async::Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Recognize_, context, request, response, std::move(f));
}

void Kaldi::Stub::experimental_async::Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kaldi::RecognizeResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Recognize_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>* Kaldi::Stub::AsyncRecognizeRaw(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::kaldi::RecognizeResponse>::Create(channel_.get(), cq, rpcmethod_Recognize_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>* Kaldi::Stub::PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::kaldi::RecognizeResponse>::Create(channel_.get(), cq, rpcmethod_Recognize_, context, request, false);
}

Kaldi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Kaldi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Kaldi::Service, ::kaldi::RecognizeRequest, ::kaldi::RecognizeResponse>(
          std::mem_fn(&Kaldi::Service::Recognize), this)));
}

Kaldi::Service::~Service() {
}

::grpc::Status Kaldi::Service::Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kaldi

