// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kaldi.proto
#ifndef GRPC_kaldi_2eproto__INCLUDED
#define GRPC_kaldi_2eproto__INCLUDED

#include "kaldi.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace kaldi {

class Kaldi final {
 public:
  static constexpr char const* service_full_name() {
    return "kaldi.Kaldi";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Performs synchronous speech recognition: receive results
    // after all audio has been sent and processed.  
    virtual ::grpc::Status Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::kaldi::RecognizeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kaldi::RecognizeResponse>> AsyncRecognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kaldi::RecognizeResponse>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kaldi::RecognizeResponse>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kaldi::RecognizeResponse>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Performs synchronous speech recognition: receive results
      // after all audio has been sent and processed.  
      virtual void Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kaldi::RecognizeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kaldi::RecognizeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kaldi::RecognizeResponse>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kaldi::RecognizeResponse>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::kaldi::RecognizeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>> AsyncRecognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response, std::function<void(::grpc::Status)>) override;
      void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kaldi::RecognizeResponse* response, std::function<void(::grpc::Status)>) override;
      void Recognize(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kaldi::RecognizeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kaldi::RecognizeResponse>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::kaldi::RecognizeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Recognize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Performs synchronous speech recognition: receive results
    // after all audio has been sent and processed.  
    virtual ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Recognize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::kaldi::RecognizeRequest* request, ::grpc::ServerAsyncResponseWriter< ::kaldi::RecognizeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Recognize<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Recognize() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::kaldi::RecognizeRequest, ::kaldi::RecognizeResponse>(
          [this](::grpc::ServerContext* context,
                 const ::kaldi::RecognizeRequest* request,
                 ::kaldi::RecognizeResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Recognize(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_Recognize(
        ::grpc::experimental::MessageAllocator< ::kaldi::RecognizeRequest, ::kaldi::RecognizeResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kaldi::RecognizeRequest, ::kaldi::RecognizeResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Recognize<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Recognize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Recognize() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Recognize() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Recognize(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Recognize(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Recognize() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::kaldi::RecognizeRequest, ::kaldi::RecognizeResponse>(std::bind(&WithStreamedUnaryMethod_Recognize<BaseClass>::StreamedRecognize, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* context, const ::kaldi::RecognizeRequest* request, ::kaldi::RecognizeResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kaldi::RecognizeRequest,::kaldi::RecognizeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Recognize<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Recognize<Service > StreamedService;
};

}  // namespace kaldi


#endif  // GRPC_kaldi_2eproto__INCLUDED
